fix: Complete elastic decomposition and M-index and simplify API
seismic-anisotropy/PyDRex pull request #139
Opened 2023-08-30 09:00 UTC by adigitoleo

Elastic decomposition now provides all symmetry component percentages.

M-index now takes into account the lattice system.
The maximum angle for random input still goes a bit over 120 degrees but
this might just be the tail of the distribution resulting from the
numerics? The mean seems to be slightly low for random input, around 80
instead of 90 degrees, but not too bad. Still, this method needs some
proper tests.

Most postprocessing functions should take a stack of orientations for a
series of texture snapshots, so NxMx3x3 orientations. In some cases
where the diagnostics are cheap to calculate this was not changed, since
it can be trivially achieved with list comprehension.

2023-08-30 09:20 UTC, adigitoleo commented
Some more notes:
- the components of the elastic decomposition look right when I check the Voigt matrices of the individual projections, however the percentages don't match Browaeys & Chevrot 2004 yet. The hexagonal % anisotrpy matches what comes out of the Fortran/original DREX code, which also doesn't match Browaeys & Chevrot 2004. I'll open an issue to flag this for later.
- the M-index should work now, well enough to attempt matching the values from Boneh et al 2015 for example. However, the equations from Grimmer to get theoretical misorientations for isotropic texture don't cover cubic crystals, which were apparently done in a previous work. Not important since olivine is orthorhombic but to be complete it could be extended to cover cubic sometime.

2023-08-30 09:38 UTC, adigitoleo commented
Ah, M-index tests need fixing, I don't think there's anywhere I can get raw CPO textures with associated M-index values (original paper has pole figures and M-indices but I'd have to see if Phil Skemer still has the data at some point). For now I'll just adjust the "expected" M-index values based on what I am able to get for say 1000 grains and then I'll bump those test down to a smaller number of grains to save CI time.

2023-09-01 07:08 UTC, Patol75 requested changes
Massive work, well done!

2023-09-01 07:08 UTC, Patol75 commented on src/pydrex/diagnostics.py
> +        This method must be able to allocate an array of shape (N choose 2)x(M**2) for N
What does `N choose 2` mean?

2023-09-03 23:35 UTC, adigitoleo commented on src/pydrex/diagnostics.py
> +        This method must be able to allocate an array of shape (N choose 2)x(M**2) for N
I put the equation instead

2023-09-04 03:29 UTC, adigitoleo commented
Fails due to missing data files, will add them soon.

2023-09-05 03:50 UTC, Patol75 approved these changes

2023-09-05 03:51 UTC, merged