test: Rework 2D simple shear ensemble test
seismic-anisotropy/PyDRex pull request #141
Opened 2023-09-05 06:36 UTC by adigitoleo

This reworks the ensemble test to be a parametrized set of ensemble tests for varying GBM, GBS and nucleation values. Plots show the effect of GBM for the chosen pair of GBS and nucleation, because GBM (M*) is the most important/least constrained of the three.

Ensemble tests don't compare to experiments nor the fortran, because these are targeted at testing the effects of the pydrex parameters specifically. I'll add a test back in vs the fortran and experiments soon.

Also here I only compute the angle diagnostic, because symmetry/strength diagnostics are expensive and don't add a lot here (I'll use separate more focused tests to compare to Boneh2015 or something).

5000 grains is good enough for steady simple shear, see #131 . I split it up using pytest parametrisation because that allows to run all cases simultaneously.

Nested `@pytest.mark.parametrize` works like `np.meshgrid`, giving all combinations. Using pytest `--collect-only` to list the expanded test list:
```shell
    <Function test_dvdx_ensemble[3-0]>
    <Function test_dvdx_ensemble[3-0.2]>
    <Function test_dvdx_ensemble[3-0.4]>
    <Function test_dvdx_ensemble[5-0]>
    <Function test_dvdx_ensemble[5-0.2]>
    <Function test_dvdx_ensemble[5-0.4]>
    <Function test_dvdx_ensemble[10-0]>
    <Function test_dvdx_ensemble[10-0.2]>
    <Function test_dvdx_ensemble[10-0.4]>
```

So each one can be selected individually in the PBS script with `-k="ensemble[3-0]"` etc.

2023-09-05 06:36 UTC, adigitoleo commented
#117

2023-09-05 09:53 UTC, Patol75 requested changes
Looking good, just two small comments on my side.

2023-09-05 09:53 UTC, Patol75 commented on tests/test_simple_shear_2d.py
> +        """Reusable logic for 2D olivine A simple shear tests.
What is going on here?

2023-09-05 09:53 UTC, Patol75 commented on tests/test_simple_shear_2d.py
> +        Returns a tuple with the mineral and the FSE angle (or `` if `return_fse` is
What do you mean by returning ``?

2023-09-05 10:14 UTC, adigitoleo commented on tests/test_simple_shear_2d.py
> +        """Reusable logic for 2D olivine A simple shear tests.
A-type Ol, typo

2023-09-05 10:15 UTC, adigitoleo commented on tests/test_simple_shear_2d.py
> +        Returns a tuple with the mineral and the FSE angle (or `` if `return_fse` is
Missing a `None`, typo

2023-09-06 00:18 UTC, Patol75 approved these changes

2023-09-06 00:18 UTC, merged