test: Add 3D shear test (Fraters 2021)
seismic-anisotropy/PyDRex pull request #158
Opened 2023-10-25 06:35 UTC by adigitoleo

Test inspired by Fraters 2021 Fig 5 but now with the correct angle projections. No figure by default because it's an ensemble, instead the data for both plots is saved for each switch time, plotting just requires loading the saved data and giving it to `visualisation.alignment`.

Other stuff included here:
- small fix to the pole figure plotting function for correct use of the optional `strains.scsv` files in some tests
- fix typo in number of grains in `mock.params_Fraters2021` (500 -> 5000)

2023-10-25 06:36 UTC, adigitoleo commented
Will run on gadi once again to confirm that it still works and then turn off draft mode.

2023-10-25 09:08 UTC, Patol75 submitted a review, later dismissed
Looking great, well done!

2023-10-26 05:55 UTC, Patol75 approved these changes

2023-11-03 06:50 UTC, Patol75 requested changes
Small typo

2023-11-03 06:50 UTC, Patol75 commented on src/pydrex/visualisation.py
> +    Additional keyword arguments are passed to the `matplotlib.axex.Axes.quiver` call
`axes.Axes`

2023-11-09 07:48 UTC, Patol75 approved these changes

2023-11-09 07:48 UTC, merged