Add Fluidity cornerflow 2d example
seismic-anisotropy/PyDRex pull request #179
Opened 2024-03-26 01:23 UTC by adigitoleo

Includes the `float32` patch to make M-index calculations less heavy.

2024-03-26 03:40 UTC, adigitoleo commented
Looks OK so far, may as well review when you get a chance. Hold off on merge, I'll handle it once I've tested for both M*=125 and M*=10.

2024-03-27 01:30 UTC, adigitoleo commented
Somehow the velocity gradient interpolation that we are doing between `velocity_grad_prev` and `velocity_gradient` is messing things up. I'll try one without interpolation (just using `velocity_gradient` as a constant for the whole step) and see what happens.

2024-03-27 04:45 UTC, adigitoleo commented
Log for case run with 5 grains, showing that interpolated gradients are not what should be expected based on the current and previous values:

<details><summary>Click to show</summary>

```
INFO [15:25] pydrex: created Mineral(phase=<MineralPhase.olivine: 0>, fabric=<MineralFabric.olivine_A: 0>, regime=<DeformationRegime.dislocation: 1>, n_grains=5, fractions=<list of ndarray (5,)>, orientations=<list of ndarray (5, 3, 3)>)
INFO [15:26] pydrex: created Mineral(phase=<MineralPhase.olivine: 0>, fabric=<MineralFabric.olivine_A: 0>, regime=<DeformationRegime.dislocation: 1>, n_grains=5, fractions=<list of ndarray (5,)>, orientations=<list of ndarray (5, 3, 3)>)
DEBUG [15:26] pydrex: velocity_gradient_prev: [9.421386935584166e-17, 0.e+00, 1.474447055418922e-17, 0.e+00, 0.e+00, 0.e+00, -6.020055549894036e-16, 0.e+00, -9.421386935584166e-17]
DEBUG [15:26] pydrex: velocity_gradient: [1.2252515907489406e-16, 0.e+00, 2.1008526833632056e-17, 0.e+00, 0.e+00, 0.e+00, -7.146271022537989e-16, 0.e+00, -1.2252515907489406e-16]
DEBUG [15:26] pydrex: deformation gradient: [1.e+00, 0.e+00, 0.e+00, 0.e+00, 1.e+00, 0.e+00, 0.e+00, 0.e+00, 1.e+00]
DEBUG [15:26] pydrex: velocity gradient [1.2252515905458136e-16, 0.e+00, 2.1008526861095287e-17, 0.e+00, 0.e+00, 0.e+00, -7.146271021729956e-16, 0.e+00, -1.2252515919901802e-16] interpolated between [1.2252515905456512e-16, 0.e+00, 2.10085268598638e-17, 0.e+00, 0.e+00, 0.e+00, -7.146271021729309e-16, 0.e+00, -1.2252515919345217e-16] and [1.225251590545976e-16, 0.e+00, 2.100852686232677e-17, 0.e+00, 0.e+00, 0.e+00, -7.146271021730602e-16, 0.e+00, -1.2252515920458388e-16]
INFO [15:26] pydrex: created Mineral(phase=<MineralPhase.olivine: 0>, fabric=<MineralFabric.olivine_A: 0>, regime=<DeformationRegime.dislocation: 1>, n_grains=5, fractions=<list of ndarray (5,)>, orientations=<list of ndarray (5, 3, 3)>)
DEBUG [15:26] pydrex: velocity_gradient_prev: [1.2252515907489406e-16, 0.e+00, 2.1008526833632056e-17, 0.e+00, 0.e+00, 0.e+00, -7.146271022537989e-16, 0.e+00, -1.2252515907489406e-16]
DEBUG [15:26] pydrex: velocity_gradient: [1.633179746404023e-16, 0.e+00, 3.109101360560365e-17, 0.e+00, 0.e+00, 0.e+00, -8.599963686753004e-16, 0.e+00, -1.633179746404023e-16]
DEBUG [15:26] pydrex: deformation gradient: [1.0053494476339215e+00, 0.e+00, 9.172322825048986e-04, 0.e+00, 1.e+00, 0.e+00, -3.1200619272350447e-02, 0.e+00, 9.946505507418922e-01]
DEBUG [15:26] pydrex: velocity gradient [2.0411079017658825e-16, 0.e+00, 4.117350041782599e-17, 0.e+00, 0.e+00, 0.e+00, -1.005365634992309e-15, 0.e+00, -2.0411079036876132e-16] interpolated between [2.0411079017655724e-16, 0.e+00, 4.117350041585469e-17, 0.e+00, 0.e+00, 0.e+00, -1.0053656349921986e-15, 0.e+00, -2.0411079036078564e-16] and [2.0411079017661923e-16, 0.e+00, 4.117350041979729e-17, 0.e+00, 0.e+00, 0.e+00, -1.0053656349924194e-15, 0.e+00, -2.0411079037673703e-16]
INFO [15:26] pydrex: created Mineral(phase=<MineralPhase.olivine: 0>, fabric=<MineralFabric.olivine_A: 0>, regime=<DeformationRegime.dislocation: 1>, n_grains=5, fractions=<list of ndarray (5,)>, orientations=<list of ndarray (5, 3, 3)>)
DEBUG [15:26] pydrex: velocity_gradient_prev: [1.633179746404023e-16, 0.e+00, 3.109101360560365e-17, 0.e+00, 0.e+00, 0.e+00, -8.599963686753004e-16, 0.e+00, -1.633179746404023e-16]
DEBUG [15:26] pydrex: velocity_gradient: [2.2330067232400195e-16, 0.e+00, 4.750961521384295e-17, 0.e+00, 0.e+00, 0.e+00, -1.0521606062769134e-15, 0.e+00, -2.2330067232400195e-16]
DEBUG [15:26] pydrex: deformation gradient: [1.014252765531233e+00, 0.e+00, 2.7134252339223387e-03, 0.e+00, 1.e+00, 0.e+00, -7.50516610233494e-02, 0.e+00, 9.857467363015732e-01]
DEBUG [15:26] pydrex: velocity gradient [3.432660676479776e-16, 0.e+00, 8.034681848947027e-17, 0.e+00, 0.e+00, 0.e+00, -1.4364890813416652e-15, 0.e+00, -3.432660679072916e-16] interpolated between [3.4326606764791563e-16, 0.e+00, 8.034681848628371e-17, 0.e+00, 0.e+00, 0.e+00, -1.4364890813414666e-15, 0.e+00, -3.4326606789565e-16] and [3.432660676480396e-16, 0.e+00, 8.034681849265685e-17, 0.e+00, 0.e+00, 0.e+00, -1.4364890813418636e-15, 0.e+00, -3.432660679189333e-16]
INFO [15:26] pydrex: created Mineral(phase=<MineralPhase.olivine: 0>, fabric=<MineralFabric.olivine_A: 0>, regime=<DeformationRegime.dislocation: 1>, n_grains=5, fractions=<list of ndarray (5,)>, orientations=<list of ndarray (5, 3, 3)>)
DEBUG [15:26] pydrex: velocity_gradient_prev: [2.2330067232400195e-16, 0.e+00, 4.750961521384295e-17, 0.e+00, 0.e+00, 0.e+00, -1.0521606062769134e-15, 0.e+00, -2.2330067232400195e-16]
DEBUG [15:26] pydrex: velocity_gradient: [3.1459363601221926e-16, 0.e+00, 7.571931766502692e-17, 0.e+00, 0.e+00, 0.e+00, -1.3101986635400144e-15, 0.e+00, -3.1459363601221926e-16]
DEBUG [15:26] pydrex: deformation gradient: [1.0291924372788321e+00, 0.e+00, 6.212042730913506e-03, 0.e+00, 1.e+00, 0.e+00, -1.3753808835162898e-01, 0.e+00, 9.708054326120437e-01]
DEBUG [15:26] pydrex: velocity gradient [5.884725270108583e-16, 0.e+00, 1.6034842510931068e-16, 0.e+00, 0.e+00, 0.e+00, -2.0843128351427334e-15, 0.e+00, -5.884725273704999e-16] interpolated between [5.884725270107259e-16, 0.e+00, 1.6034842510389086e-16, 0.e+00, 0.e+00, 0.e+00, -2.084312835142359e-15, 0.e+00, -5.884725273529601e-16] and [5.884725270109909e-16, 0.e+00, 1.603484251147305e-16, 0.e+00, 0.e+00, 0.e+00, -2.0843128351431077e-15, 0.e+00, -5.884725273880396e-16]
INFO [15:26] pydrex: created Mineral(phase=<MineralPhase.olivine: 0>, fabric=<MineralFabric.olivine_A: 0>, regime=<DeformationRegime.dislocation: 1>, n_grains=5, fractions=<list of ndarray (5,)>, orientations=<list of ndarray (5, 3, 3)>)
DEBUG [15:26] pydrex: velocity_gradient_prev: [3.1459363601221926e-16, 0.e+00, 7.571931766502692e-17, 0.e+00, 0.e+00, 0.e+00, -1.3101986635400144e-15, 0.e+00, -3.1459363601221926e-16]
DEBUG [15:26] pydrex: velocity_gradient: [4.586841643196328e-16, 0.e+00, 1.2653270996739015e-16, 0.e+00, 0.e+00, 0.e+00, -1.66383612422832e-15, 0.e+00, -4.586841643196328e-16]
DEBUG [15:26] pydrex: deformation gradient: [1.054684254449256e+00, 0.e+00, 1.316817176295027e-02, 0.e+00, 1.e+00, 0.e+00, -2.2766393453187123e-01, 0.e+00, 9.453085907671755e-01]
DEBUG [15:26] pydrex: velocity gradient [1.035046277444583e-15, 0.e+00, 3.297862793208907e-16, 0.e+00, 0.e+00, 0.e+00, -3.0783859667245697e-15, 0.e+00, -1.03504627795776e-15] interpolated between [1.0350462774442778e-15, 0.e+00, 3.29786279311268e-16, 0.e+00, 0.e+00, 0.e+00, -3.078385966723821e-15, 0.e+00, -1.0350462779304731e-15] and [1.035046277444888e-15, 0.e+00, 3.2978627933051343e-16, 0.e+00, 0.e+00, 0.e+00, -3.0783859667253187e-15, 0.e+00, -1.0350462779850471e-15]
INFO [15:27] pydrex: created Mineral(phase=<MineralPhase.olivine: 0>, fabric=<MineralFabric.olivine_A: 0>, regime=<DeformationRegime.dislocation: 1>, n_grains=5, fractions=<list of ndarray (5,)>, orientations=<list of ndarray (5, 3, 3)>)
DEBUG [15:27] pydrex: velocity_gradient_prev: [4.586841643196328e-16, 0.e+00, 1.2653270996739015e-16, 0.e+00, 0.e+00, 0.e+00, -1.66383612422832e-15, 0.e+00, -4.586841643196328e-16]
DEBUG [15:27] pydrex: velocity_gradient: [6.966422539978852e-16, 0.e+00, 2.2541712862763944e-16, 0.e+00, 0.e+00, 0.e+00, -2.1542033829362136e-15, 0.e+00, -6.966422539978852e-16]
DEBUG [15:27] pydrex: deformation gradient: [1.0991247486958917e+00, 0.e+00, 2.7375196956775698e-02, 0.e+00, 1.e+00, 0.e+00, -3.5914231616262343e-01, 0.e+00, 9.008699124342225e-01]
DEBUG [15:27] pydrex: velocity gradient [1.8864327022149598e-15, 0.e+00, 7.198392221721506e-16, 0.e+00, 0.e+00, 0.e+00, -4.606039676116728e-15, 0.e+00, -1.886432702974546e-15] interpolated between [1.88643270221419e-15, 0.e+00, 7.198392221538205e-16, 0.e+00, 0.e+00, 0.e+00, -4.606039676115142e-15, 0.e+00, -1.886432702930436e-15] and [1.8864327022157297e-15, 0.e+00, 7.198392221904807e-16, 0.e+00, 0.e+00, 0.e+00, -4.6060396761183155e-15, 0.e+00, -1.886432703018656e-15]
INFO [15:27] pydrex: created Mineral(phase=<MineralPhase.olivine: 0>, fabric=<MineralFabric.olivine_A: 0>, regime=<Deforma [...]

2024-03-27 07:04 UTC, adigitoleo commented
Running postprocessing again now, but this should be good to go.

2024-03-27 18:49 UTC, adigitoleo commented
Confirming that it works (for the 1 pathline) for both M*=10 and M*=125 and results are close to standalone equivalents. Quickly checking if the multi-particle crash has persisted.

2024-03-27 19:31 UTC, adigitoleo commented
Multi-particle is not crashing anymore. I'll push a commit to add the other spawn locations.

2024-03-28 02:30 UTC, Patol75 requested changes
Awesome! Just one typo ;)

2024-03-28 02:30 UTC, Patol75 commented on src/pydrex/minerals.py
> +          returns a 3x3 velocity gradient matrix at time t at position x (3D vector)
`at time t and position x`

2024-03-28 02:44 UTC, Patol75 approved these changes

2024-03-28 03:02 UTC, merged